# Generated by Django 4.0 on 2022-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20220118_2059'),
        ('labtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtests',
            name='patient',
            field=models.ManyToManyField(to='appointment.Patient'),
        ),
    ]
