# Generated by Django 4.0 on 2022-01-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0002_labtests_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=50)),
                ('labtestname', models.CharField(max_length=50)),
                ('bill', models.IntegerField()),
            ],
        ),
    ]
