# Generated by Django 3.2.6 on 2022-01-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20220118_2059'),
        ('labtest', '0003_labbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbilling',
            name='LabTests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labtest.labtests'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labbilling',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appointment.patient'),
            preserve_default=False,
        ),
    ]
