# Generated by Django 3.2.6 on 2022-01-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20220118_2059'),
        ('labtest', '0004_auto_20220120_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labbilling',
            old_name='LabTests',
            new_name='labTests',
        ),
        migrations.AlterField(
            model_name='labtests',
            name='patient',
            field=models.ManyToManyField(null=True, to='appointment.Patient'),
        ),
    ]
