# Generated by Django 3.2.6 on 2022-01-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0005_auto_20220120_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtests',
            name='patient',
        ),
        migrations.AlterField(
            model_name='labbilling',
            name='bill',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='labbilling',
            name='labtestname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labbilling',
            name='patientname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
